// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoaDlMtsIsdtbUA_I4VZ1RqqIuRgANUh0',
    appId: '1:501890933663:web:9026be13ce3cbbf31913aa',
    messagingSenderId: '501890933663',
    projectId: 'flutter-68899',
    authDomain: 'flutter-68899.firebaseapp.com',
    storageBucket: 'flutter-68899.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhtchhq_VqI1ko3Nh7qJZ-iI_HwFRRt_A',
    appId: '1:501890933663:android:b7e70d4aae6fc6591913aa',
    messagingSenderId: '501890933663',
    projectId: 'flutter-68899',
    storageBucket: 'flutter-68899.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Kasdgu2ndSmI3EwZCWlFABMX_w7oVhY',
    appId: '1:501890933663:ios:ba85b2c99d0bc4451913aa',
    messagingSenderId: '501890933663',
    projectId: 'flutter-68899',
    storageBucket: 'flutter-68899.appspot.com',
    iosClientId: '501890933663-5bdb5ln8boc1mru2giltad3jsps1q909.apps.googleusercontent.com',
    iosBundleId: 'com.amine.app',
  );
}
